# Generated by Django 5.2.3 on 2025-09-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
